name: Release
# .github/workflows/release.yaml

on: 
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm]
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.11
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: "1.15"
        project_path: "./cmd/sgp4go"
        binary_name: "sgp4go"
        extra_files: LICENSE README.md
